struct AppStrings: Equatable {
  let selectMode: String
  let parentMode: String
  let parentModeSubtitle: String
  let universalMode: String
  let universalModeSubtitle: String
  let deepAnalysis: String
  let deepAnalysisSubtitle: String
  let history: String
  let settings: String
  let onboardingText1: String
  let onboardingText2: String
  let next: String
  let start: String
  let privacyAndConsent: String
  let consentDescription: String
  let consentVoice: String
  let consentPrivacy: String
  let consentCardSummary: String
  let readFullPrivacyPolicy: String
  let privacyPolicyShortLink: String
  let consentOpenPrivacyPolicyButton: String
  let privacyPolicyFullTitle: String
  let privacyPolicyFullEnglishNote: String
  let back: String
  let voiceRecording: String
  let recordingInProgress: String
  let tapToStart: String
  let tapToStop: String
  let saySentences: String
  let secondsShort: String
  let durationHint: String
  let uploadAudio: String
  let uploadAudioError: String
  let micPermissionRequired: String
  let recordingStartFailed: String
  let recordingEmptyFile: String
  let analyzing: String
  let analyzingSubtitle: String
  let analyzeRetry: String
  let result: String
  let emotionalBackground: String
  let stressLevel: String
  let innerAnxiety: String
  let resource: String
  let tense: String
  let medium: String
  let mediumF: String
  let reduced: String
  let share: String
  let newAnalysis: String
  let statesChart: String
  let goHome: String
  let emostateResultTitle: String
  let emostateParameters: String
  let emostateReportTitle: String
  let resultHintTitle: String
  let emostateParamHintFallback: String
  let emostateGeneralDisclaimerTitle: String
  let emostateGeneralDisclaimerBody: String
  let emostateReportInfoSheetTitle: String
  let psytypeResultTitle: String
  let leadingType: String
  let activeType: String
  let psytypeAllTypes: String
  let psytypeReportTitle: String
  let shareResult: String
  let shareNoData: String
  let shareSubject: String
  let link: String
  let more: String
  let state: String
  let stableLightTension: String
  let historyTitle: String
  let today: String
  let yesterday: String
  let daysAgo: String
  let twoDaysAgo: String
  let lightTension: String
  let stable: String
  let overload: String
  let low: String
  let high: String
  let stressLabel: String
  let historyTypeEmostate: String
  let historyTypePsytype: String
  let historyEmpty: String
  let statisticsButton: String
  let statisticsTitle: String
  let statisticsPeriodWeek: String
  let statisticsPeriodMonth: String
  let statisticsPeriod24h: String
  let statisticsPeriodCustom: String
  let statisticsDateFrom: String
  let statisticsDateTo: String
  let statisticsNoData: String
  let settingsTitle: String
  let themeTitle: String
  let themeGlass: String
  let themeLight: String
  let about: String
  let help: String
  let language: String
  let selectLanguage: String
  let languageRu: String
  let languageEn: String
  let languageZh: String
  let languageKz: String
  let languageUk: String
  let languageKa: String
  let aboutTitle: String
  let aboutDescription: String
  let aboutBriefSectionTitle: String
  let aboutFullDescriptionButton: String
  let aboutPresentationNext: String
  let aboutPresentationDone: String
  let aboutResearchLinksTitle: String
  let helpTitle: String
  let helpSubtitle: String
  let helpQuickStartTitle: String
  let helpQuickStartBody: String
  let helpRecordingTitle: String
  let helpRecordingBody: String
  let helpModesTitle: String
  let helpModesBody: String
  let helpResultsTitle: String
  let helpResultsBody: String
  let helpPrivacyTitle: String
  let helpPrivacyBody: String
  let helpTroubleshootTitle: String
  let helpTroubleshootBody: String
  let forBusiness: String
  let forBusinessTitle: String
  let forBusinessIntro: String
  let forBusinessBullet1: String
  let forBusinessBullet2: String
  let forBusinessBullet3: String
  let forBusinessBullet4: String
  let forBusinessBullet5: String
  let forBusinessBullet6: String
  let forBusinessOutro: String
  let fillQuestionnaire: String
  let questionnaireTitle: String
  let purposeOfUse: String
  let purposeFinancial: String
  let purposeHrSports: String
  let purposeSafety: String
  let purposeOther: String
  let orgName: String
  let fieldOfActivity: String
  let contacts: String
  let contactsFio: String
  let contactsEmail: String
  let contactsPhone: String
  let approxClientsPerDay: String
  let approxPeopleAndFrequency: String
  let fieldAndGoal: String
  let approxEmployeesPerDay: String
  let approxEmployeesPerDayMonth: String
  let specialConditions: String
  let submitQuestionnaire: String
  let questionnaireEmailSubject: String
  let questionnaireEmailChooserTitle: String
  let questionnaireNoEmailApp: String
  let questionnaireIncomplete: String
  let questionnaireEmailSentAt: String
  let questionnaireEmailFooter: String
  let profile: String
  let manageSubscriptions: String
  let profileTitle: String
  let userName: String
  let planBasic: String
  let planBasicDesc: String
  let planStandard: String
  let planStandardDesc: String
  let planPro: String
  let planProDesc: String
  let planUnlimited: String
  let planUnlimitedDesc: String
  let planBusiness: String
  let planBusinessDesc: String
  let currentPlan: String
  let profileNameLabel: String
  let profilePhoneLabel: String
  let profileEmailLabel: String
  let profilePaymentLabel: String
  let profilePhoneValue: String
  let profileEmailValue: String
  let profilePaymentValue: String
  let authTitle: String
  let authEmail: String
  let authPassword: String
  let authPasswordConfirm: String
  let authRememberPassword: String
  let authLogin: String
  let authRegister: String
  let authGoogle: String
  let authSkip: String
  let authRegisterHint: String
  let authLoginHint: String
  let authForgotPassword: String
  let authResetEmailSent: String
  let authVerifyEmailSent: String
  let authEmailNotVerified: String
  let authResendVerification: String
  let authErrorInvalidEmail: String
  let authErrorWeakPassword: String
  let authErrorPasswordMismatch: String
  let authErrorWrongPassword: String
  let authErrorUserNotFound: String
  let authErrorEmailInUse: String
  let authErrorGeneric: String
  let profileEditTitle: String
  let profileChangePhoto: String
  let profileSignOut: String
  let profileGuestTitle: String
  let profileGuestName: String
  let profileDone: String
}
