#!/bin/bash
# Injects VOXERA_API_TOKEN into Generated/APIToken.generated.swift (Debug + Release/TestFlight).
# Reads Voxera/Secrets.xcconfig (and a few fallback paths). Does not rely on Scheme env vars.
set -eu

ROOT="${SRCROOT:-}"
if [[ -z "$ROOT" ]]; then
  ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi

OUT="$ROOT/Voxera/Generated/APIToken.generated.swift"
mkdir -p "$(dirname "$OUT")"

extract_token() {
  local file="$1"
  [[ -f "$file" ]] || return 1
  # Strip UTF-8 BOM / CR; take last VOXERA_API_TOKEN assignment.
  local line
  line=$(
    tr -d '\r' <"$file" \
      | sed $'1s/^\xEF\xBB\xBF//' \
      | grep -E '^[[:space:]]*VOXERA_API_TOKEN[[:space:]]*=' \
      | tail -1 \
    || true
  )
  [[ -n "$line" ]] || return 1
  printf '%s' "$line" | sed 's/^[^=]*=[[:space:]]*//' | sed 's/[[:space:]]*$//'
}

TOKEN=""
# Build setting (only if Xcode exports it — often empty in script phases).
if [[ -n "${VOXERA_API_TOKEN:-}" ]]; then
  TOKEN="$VOXERA_API_TOKEN"
fi

CANDIDATES=(
  "$ROOT/Voxera/Secrets.xcconfig"
  "$ROOT/Secrets.xcconfig"
  "${PROJECT_DIR:-}/Voxera/Secrets.xcconfig"
  "${PROJECT_DIR:-}/Secrets.xcconfig"
)

# Last resort: people sometimes paste the token into the .example file in Xcode.
FALLBACK_EXAMPLE="$ROOT/Voxera/Secrets.xcconfig.example"

echo "note: GenerateAPIToken SRCROOT=${ROOT}"
for f in "${CANDIDATES[@]}"; do
  [[ -n "$f" ]] || continue
  if [[ -f "$f" ]]; then
    echo "note: found secrets file: $f"
    if GOT=$(extract_token "$f"); then
      if [[ -n "$GOT" && "$GOT" != "paste_token_here" && "$GOT" != "your_token_here" ]]; then
        TOKEN="$GOT"
        echo "note: parsed token from $f (length=${#TOKEN})"
        break
      fi
    fi
  else
    echo "note: missing: $f"
  fi
done

if [[ -z "$TOKEN" && -f "$FALLBACK_EXAMPLE" ]]; then
  if GOT=$(extract_token "$FALLBACK_EXAMPLE"); then
    if [[ -n "$GOT" && "$GOT" != "paste_token_here" && "$GOT" != "your_token_here" ]]; then
      TOKEN="$GOT"
      echo "warning: token was read from Secrets.xcconfig.example — copy it to Secrets.xcconfig (gitignored)."
    fi
  fi
fi

# Strip accidental quotes
case "$TOKEN" in
  \"*\") TOKEN="${TOKEN:1:${#TOKEN}-2}" ;;
  \'*\') TOKEN="${TOKEN:1:${#TOKEN}-2}" ;;
esac

TOKEN_ESC=$(printf '%s' "$TOKEN" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

cat >"$OUT" <<EOF
// Generated by scripts/GenerateAPIToken.sh — do not edit by hand.
enum APIToken {
  static let value: String = "${TOKEN_ESC}"
}
EOF

echo "note: wrote $OUT (token length=${#TOKEN})"

if [[ "${CONFIGURATION:-Debug}" == "Release" && -z "$TOKEN" ]]; then
  echo "error: VOXERA_API_TOKEN is empty for Release/TestFlight."
  echo "error: Expected file at: $ROOT/Voxera/Secrets.xcconfig"
  echo "error: Contents must include a line: VOXERA_API_TOKEN = your_token"
  echo "error: (Scheme Environment Variables are NOT used for Archive/TestFlight.)"
  ls -la "$ROOT/Voxera" 2>/dev/null || true
  exit 1
fi
