#!/bin/bash
# Bake VOXERA_API_TOKEN into Generated/APIToken.generated.swift
# Must tolerate unset env vars (Xcode Archive often has no VOXERA_API_TOKEN in the environment).

ROOT="${SRCROOT:-}"
if [ -z "$ROOT" ]; then
  ROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi

OUT="$ROOT/Voxera/Generated/APIToken.generated.swift"
SECRETS="$ROOT/Voxera/Secrets.xcconfig"
EXAMPLE="$ROOT/Voxera/Secrets.xcconfig.example"
mkdir -p "$(dirname "$OUT")"

TOKEN="${VOXERA_API_TOKEN-}"

extract_token() {
  # $1 = file path. Prints token or empty. Always exit 0.
  local f="$1"
  if [ ! -f "$f" ]; then
    return 0
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 -c '
import re, sys
path = sys.argv[1]
raw = open(path, "rb").read()
if raw.startswith(b"\xff\xfe") or raw.startswith(b"\xfe\xff"):
    text = raw.decode("utf-16")
elif raw.startswith(b"\xef\xbb\xbf"):
    text = raw[3:].decode("utf-8", errors="replace")
elif b"\x00" in raw[:200]:
    try:
        text = raw.decode("utf-16-le")
    except Exception:
        text = raw.decode("utf-8", errors="replace")
else:
    text = raw.decode("utf-8", errors="replace")
text = text.replace("\r\n", "\n").replace("\r", "\n")
token = ""
for raw_line in text.splitlines():
    line = raw_line.strip()
    if not line or line.startswith("//") or line.startswith("#"):
        continue
    m = re.match(r"^VOXERA_API_TOKEN\s*=\s*(.*)$", line, re.I)
    if not m:
        continue
    val = m.group(1).strip().strip("\"'\''")
    if "//" in val:
        val = val.split("//", 1)[0].rstrip()
    if val and val not in ("paste_token_here", "your_token_here"):
        token = val
sys.stdout.write(token)
' "$f" || true
    return 0
  fi
  # grep fallback
  local line val
  line=$(tr -d '\r' <"$f" | grep -iE '^[[:space:]]*VOXERA_API_TOKEN[[:space:]]*=' | tail -1 || true)
  if [ -n "$line" ]; then
    val=$(printf '%s' "$line" | sed 's/^[^=]*=[[:space:]]*//' | sed 's/[[:space:]]*$//' | sed 's/^"//;s/"$//')
    printf '%s' "$val"
  fi
}

if [ -z "$TOKEN" ] || [ "$TOKEN" = "paste_token_here" ] || [ "$TOKEN" = "your_token_here" ]; then
  TOKEN="$(extract_token "$SECRETS")"
fi
if [ -z "$TOKEN" ]; then
  TOKEN="$(extract_token "$EXAMPLE")"
  if [ -n "$TOKEN" ]; then
    echo "warning: token read from Secrets.xcconfig.example; prefer Secrets.xcconfig"
  fi
fi

echo "note: GenerateAPIToken secrets=$SECRETS token_len=${#TOKEN}"

TOKEN_ESC=$(printf '%s' "$TOKEN" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

cat >"$OUT" <<EOF
// Generated by scripts/GenerateAPIToken.sh — do not edit by hand.
enum APIToken {
  static let value: String = "${TOKEN_ESC}"
}
EOF

CONFIG="${CONFIGURATION-Debug}"
if [ "$CONFIG" = "Release" ] && [ -z "$TOKEN" ]; then
  echo "error: VOXERA_API_TOKEN empty for Release. Put in $SECRETS :"
  echo "error: VOXERA_API_TOKEN = your_token"
  exit 1
fi

exit 0
