package com.vanoprojects.voxera.ui.strings

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage { RU, EN, ZH, KZ }

val LocalStrings = compositionLocalOf { Strings.Ru }

data class Strings(
    // ModeSelect
    val selectMode: String,
    val parentMode: String,
    val parentModeSubtitle: String,
    val universalMode: String,
    val universalModeSubtitle: String,
    val deepAnalysis: String,
    val deepAnalysisSubtitle: String,
    val history: String,
    val settings: String,
    val onboardingText1: String,
    val onboardingText2: String,
    val next: String,
    val start: String,
    // Consent
    val privacyAndConsent: String,
    val consentDescription: String,
    val consentVoice: String,
    val consentPrivacy: String,
    /** Краткий текст на карточке согласия; полная политика открывается отдельно. */
    val consentCardSummary: String,
    val readFullPrivacyPolicy: String,
    /** Короткая подпись ссылки и кнопки в настройках: «Политика конфиденциальности». */
    val privacyPolicyShortLink: String,
    /** Компактная кнопка на экране согласия под галочками. */
    val consentOpenPrivacyPolicyButton: String,
    val privacyPolicyFullTitle: String,
    /** Подзаголовок: полный юридический текст на английском. */
    val privacyPolicyFullEnglishNote: String,
    val back: String,
    // Recording
    val voiceRecording: String,
    val recordingInProgress: String,
    val tapToStart: String,
    val tapToStop: String,
    val saySentences: String,
    val secondsShort: String,
    val durationHint: String,
    val uploadAudio: String,
    val uploadAudioError: String,
    val micPermissionRequired: String,
    val recordingStartFailed: String,
    val recordingEmptyFile: String,
    // Processing
    val analyzing: String,
    val analyzingSubtitle: String,
    // Result
    val result: String,
    val emotionalBackground: String,
    val stressLevel: String,
    val innerAnxiety: String,
    val resource: String,
    val tense: String,
    val medium: String,
    val mediumF: String,
    val reduced: String,
    val share: String,
    val newAnalysis: String,
    val emostateResultTitle: String,
    val emostateParameters: String,
    val emostateReportTitle: String,
    val resultHintTitle: String,
    val emostateParamHintFallback: String,
    val emostateGeneralDisclaimerTitle: String,
    val emostateGeneralDisclaimerBody: String,
    val emostateReportInfoSheetTitle: String,
    val psytypeResultTitle: String,
    val leadingType: String,
    val activeType: String,
    val psytypeAllTypes: String,
    val psytypeReportTitle: String,
    // Share
    val shareResult: String,
    val shareNoData: String,
    val shareSubject: String,
    val link: String,
    val more: String,
    val state: String,
    val stableLightTension: String,
    // History
    val historyTitle: String,
    val today: String,
    val yesterday: String,
    val daysAgo: String,
    val twoDaysAgo: String,
    val lightTension: String,
    val stable: String,
    val overload: String,
    val low: String,
    val high: String,
    val stressLabel: String,
    val historyTypeEmostate: String,
    val historyTypePsytype: String,
    val historyEmpty: String,
    val statisticsButton: String,
    val statisticsTitle: String,
    val statisticsPeriodWeek: String,
    val statisticsPeriodMonth: String,
    val statisticsNoData: String,
    // Settings
    val settingsTitle: String,
    val themeTitle: String,
    val themeGlass: String,
    val themeLight: String,
    val about: String,
    val help: String,
    val language: String,
    val selectLanguage: String,
    val languageRu: String,
    val languageEn: String,
    val languageZh: String,
    val languageKz: String,
    // About
    val aboutTitle: String,
    val aboutDescription: String,
    val aboutBriefSectionTitle: String,
    val aboutFullDescriptionButton: String,
    val aboutPresentationNext: String,
    val aboutPresentationDone: String,
    val aboutResearchLinksTitle: String,
    // Help
    val helpTitle: String,
    val helpSubtitle: String,
    val helpQuickStartTitle: String,
    val helpQuickStartBody: String,
    val helpRecordingTitle: String,
    val helpRecordingBody: String,
    val helpModesTitle: String,
    val helpModesBody: String,
    val helpResultsTitle: String,
    val helpResultsBody: String,
    val helpPrivacyTitle: String,
    val helpPrivacyBody: String,
    val helpTroubleshootTitle: String,
    val helpTroubleshootBody: String,
    // For Business
    val forBusiness: String,
    val forBusinessTitle: String,
    val forBusinessIntro: String,
    val forBusinessBullet1: String,
    val forBusinessBullet2: String,
    val forBusinessBullet3: String,
    val forBusinessBullet4: String,
    val forBusinessBullet5: String,
    val forBusinessBullet6: String,
    val forBusinessOutro: String,
    val fillQuestionnaire: String,
    val questionnaireTitle: String,
    val purposeOfUse: String,
    val purposeFinancial: String,
    val purposeHrSports: String,
    val purposeSafety: String,
    val purposeOther: String,
    val orgName: String,
    val fieldOfActivity: String,
    val contacts: String,
    val contactsFio: String,
    val contactsEmail: String,
    val contactsPhone: String,
    val approxClientsPerDay: String,
    val approxPeopleAndFrequency: String,
    val fieldAndGoal: String,
    val approxEmployeesPerDay: String,
    val approxEmployeesPerDayMonth: String,
    val specialConditions: String,
    val submitQuestionnaire: String,
    val questionnaireEmailSubject: String,
    val questionnaireEmailChooserTitle: String,
    val questionnaireNoEmailApp: String,
    val questionnaireIncomplete: String,
    val questionnaireEmailSentAt: String,
    val questionnaireEmailFooter: String,
    // Profile
    val profile: String,
    val manageSubscriptions: String,
    val profileTitle: String,
    val userName: String,
    val planBasic: String,
    val planBasicDesc: String,
    val planStandard: String,
    val planStandardDesc: String,
    val planPro: String,
    val planProDesc: String,
    val planUnlimited: String,
    val planUnlimitedDesc: String,
    val planBusiness: String,
    val planBusinessDesc: String,
    val currentPlan: String,
    val profileNameLabel: String,
    val profilePhoneLabel: String,
    val profileEmailLabel: String,
    val profilePaymentLabel: String,
    val profilePhoneValue: String,
    val profileEmailValue: String,
    val profilePaymentValue: String,
    // Auth
    val authTitle: String,
    val authEmail: String,
    val authPassword: String,
    val authLogin: String,
    val authRegister: String,
    val authGoogle: String,
    val authSkip: String,
    val authRegisterHint: String,
    val authLoginHint: String,
    val authErrorInvalidEmail: String,
    val authErrorWeakPassword: String,
    val authErrorWrongPassword: String,
    val authErrorUserNotFound: String,
    val authErrorEmailInUse: String,
    val authErrorGeneric: String,
    val profileEditTitle: String,
    val profileChangePhoto: String,
    val profileSignOut: String,
    val profileGuestTitle: String,
    val profileGuestName: String,
    val profileDone: String
) {
    companion object {
        val Ru = Strings(
            selectMode = "Выберите режим",
            parentMode = "Родительский режим",
            parentModeSubtitle = "Психоэмоциональное состояние подростка от 12 лет",
            universalMode = "Универсальный режим",
            universalModeSubtitle = "Психоэмоциональное состояние человека",
            deepAnalysis = "Глубокий анализ",
            deepAnalysisSubtitle = "Создание и оценка психологического портрета человека",
            history = "История",
            settings = "Настройки",
            onboardingText1 = "Voxera — это AI-экосистема голосовой аналитики. Алгоритмы искусственного интеллекта обрабатывают параметры речи и формируют цифровой профиль психоэмоционального состояния, помогая лучше понимать себя и управлять своим состоянием",
            onboardingText2 = "Голос — это не просто слова: он отражает работу дыхания, мышц, нервной системы и эмоций. Именно эти признаки Voxera анализирует, чтобы понять ваш уровень стресса, эмоциональный фон, когнитивную нагрузку, энергетическое состояние и стабильность поведения.",
            next = "Далее",
            start = "Начать",
            privacyAndConsent = "Приватность и согласие",
            consentDescription = "Voxera анализирует голосовые признаки для оценки текущего состояния. Это не медицинский диагноз.",
            consentVoice = "Я согласен(а) на обработку голосовых данных для анализа",
            consentPrivacy = "Я принимаю Политику конфиденциальности и обработки данных",
            consentCardSummary =
                "Кратко: VOICElab обрабатывает аудио и технические данные в приложении Voxera для предоставления анализа. " +
                "Это не медицинский диагноз. Полный текст политики — по ссылке ниже; при желании откройте и прочитайте, затем отметьте пункты.",
            readFullPrivacyPolicy = "Открыть полную политику конфиденциальности",
            privacyPolicyShortLink = "Политика конфиденциальности",
            consentOpenPrivacyPolicyButton = "Ознакомиться с политикой конфиденциальности",
            privacyPolicyFullTitle = "Политика конфиденциальности и обработки данных",
            privacyPolicyFullEnglishNote = "Полный юридический текст на английском языке.",
            back = "Назад",
            voiceRecording = "Запись голоса",
            recordingInProgress = "Идет запись...",
            tapToStart = "Нажмите на кнопку и говорите в течение 30 секунд на любые темы",
            tapToStop = "Нажмите кнопку чтобы остановить запись",
            saySentences = "Например, можете говорить о погоде, или как прошел ваш день",
            secondsShort = "сек",
            durationHint = "Минимум 30 секунд",
            uploadAudio = "Загрузить аудио",
            uploadAudioError = "Не удалось загрузить файл",
            micPermissionRequired = "Нужен доступ к микрофону для записи",
            recordingStartFailed = "Не удалось начать запись",
            recordingEmptyFile = "Запись пуста или слишком короткая — попробуйте ещё раз",
            analyzing = "Анализируем",
            analyzingSubtitle = "Это займёт несколько секунд",
            result = "Результат",
            emotionalBackground = "Эмоциональный фон",
            stressLevel = "Уровень стресса",
            innerAnxiety = "Внутренняя тревожность",
            resource = "Ресурс",
            tense = "Напряжённый",
            medium = "Средний",
            mediumF = "Средняя",
            reduced = "Снижен",
            share = "Поделиться",
            newAnalysis = "Новый анализ",
            emostateResultTitle = "Результаты анализа психоэмоционального состояния",
            emostateParameters = "Параметры",
            emostateReportTitle = "Отчет по психоэмоциональному состоянию",
            resultHintTitle = "Подсказка",
            emostateParamHintFallback =
                "Показатель отражает один из аспектов голосового профиля в текущем контексте. " +
                "Смотрите на значения в совокупности с остальными метриками.",
            emostateGeneralDisclaimerTitle = "Общая подсказка",
            emostateGeneralDisclaimerBody =
                "Результаты основаны на анализе голоса и отражают текущее состояние.\n" +
                "Значения могут меняться в зависимости от самочувствия и контекста.",
            emostateReportInfoSheetTitle = "Интерпретация метрик и состояний",
            psytypeResultTitle = "Результаты анализа психотипа",
            leadingType = "Ведущий тип",
            activeType = "Активный тип",
            psytypeAllTypes = "Все типы",
            psytypeReportTitle = "Описание",
            shareResult = "Поделиться результатом",
            shareNoData = "Нет данных для публикации",
            shareSubject = "Voxera — результат анализа",
            link = "Ссылка",
            more = "Ещё…",
            state = "Состояние",
            stableLightTension = "Стабильнее, лёгкое напряжение",
            historyTitle = "История",
            today = "Сегодня",
            yesterday = "Вчера",
            daysAgo = "дней назад",
            twoDaysAgo = "2 дня назад",
            lightTension = "Лёгкое напряжение",
            stable = "Стабильное",
            overload = "Перегруз",
            low = "Низкий",
            high = "Высокий",
            stressLabel = "Стресс",
            historyTypeEmostate = "Психоэмоциональное состояние",
            historyTypePsytype = "Психологический портрет",
            historyEmpty = "История пуста",
            statisticsButton = "Статистика",
            statisticsTitle = "Статистика",
            statisticsPeriodWeek = "Неделя",
            statisticsPeriodMonth = "Месяц",
            statisticsNoData = "Недостаточно данных для графика. Добавьте результаты анализа психоэмоционального состояния.",
            settingsTitle = "Настройки",
            themeTitle = "Тема оформления",
            themeGlass = "Стеклянная",
            themeLight = "Светлая",
            about = "О приложении",
            help = "Помощь",
            language = "Язык",
            selectLanguage = "Выберите язык:",
            languageRu = "Русский",
            languageEn = "English",
            languageZh = "中文",
            languageKz = "Қазақша",
            aboutTitle = "О приложении",
            aboutDescription = "Экспериментальный анализ состояния по голосу. Не является медицинским диагнозом.",
            aboutBriefSectionTitle = "Краткое описание",
            aboutFullDescriptionButton = "Полное описание",
            aboutPresentationNext = "Далее",
            aboutPresentationDone = "Готово",
            aboutResearchLinksTitle = "Ссылки на исследования",
            helpTitle = "Помощь",
            helpSubtitle = "Подсказки по шагам: от выбора режима до истории и устранения неполадок.",
            helpQuickStartTitle = "Быстрый старт",
            helpQuickStartBody = "На главном экране выберите режим анализа. При необходимости войдите в аккаунт. На экране записи примите согласие на обработку голоса, затем нажмите кнопку записи и говорите спокойно не менее 30 секунд — ориентируйтесь на подсказки на экране. После обработки откроется карточка результата.",
            helpRecordingTitle = "Запись и загрузка файла",
            helpRecordingBody = "Говорите в естественном темпе, без шёпота и без крика. Держите телефон на комфортном расстоянии от рта. Если удобнее использовать готовый файл — нажмите «Загрузить аудио» и выберите поддерживаемый формат (например WAV, MP3, M4A). Длительность записи должна соответствовать требованиям сервиса: слишком короткий фрагмент может быть отклонён.",
            helpModesTitle = "Режимы анализа",
            helpModesBody = "Доступны сценарии для разных целей: быстрый анализ, отдельные пользовательские режимы и вариант с психологическим портретом. Перед записью показывается краткое описание выбранного режима.",
            helpResultsTitle = "Результат и история",
            helpResultsBody = "На экране результата отображаются основные показатели состояния, уровень стресса и тревожности. История анализов хранится на устройстве — оттуда можно открыть прошлые записи.",
            helpPrivacyTitle = "Конфиденциальность и обмен",
            helpPrivacyBody = "Запись используется для анализа в рамках выбранного сценария.",
            helpTroubleshootTitle = "Если что-то пошло не так",
            helpTroubleshootBody = "Проверьте интернет и разрешение на микрофон. Попробуйте записать в более тихом месте. При загрузке файла убедитесь в поддерживаемом формате и достаточной длине. Если ошибка повторяется — попробуйте позже или другой фрагмент речи.",
            forBusiness = "Для бизнеса",
            forBusinessTitle = "Для бизнеса",
            forBusinessIntro = "На данном этапе мы реализуем индивидуальный подход к B2B. Наша команда готова предложить вам различные опции по использованию данного продукта, например:",
            forBusinessBullet1 = "оценка психоэмоционального состояния ваших клиентов в моменте (финансовые, кредитные организации),",
            forBusinessBullet2 = "оценка психоэмоциональной атмосферы коллектива сотрудников,",
            forBusinessBullet3 = "оценка усталости и степень выгорания сотрудников,",
            forBusinessBullet4 = "оценка психоэмоционального состояния сотрудников, занимающих ответственные посты и выполняющих ответственные функции и задачи,",
            forBusinessBullet5 = "оценка психоэмоционального состояния групп детей в образовательных системах,",
            forBusinessBullet6 = "оценка психоэмоционального состояния спортсменов.",
            forBusinessOutro = "Мы подготовим предложение именно для вашей сферы деятельности, а при необходимости — интегрируем наш продукт в ваши ИТ-системы.\n\nЧтобы понять ваши потребности, заполните, пожалуйста, короткую анкету:",
            fillQuestionnaire = "Заполнить анкету",
            questionnaireTitle = "Анкета",
            purposeOfUse = "Цель использования продукта",
            purposeFinancial = "Финансовые организации для оценки клиентов",
            purposeHrSports = "HR, спорт и образовательные системы",
            purposeSafety = "Безопасность и ответственные функции сотрудников",
            purposeOther = "Другое",
            orgName = "Название организации",
            fieldOfActivity = "Сфера деятельности",
            contacts = "Контакты",
            contactsFio = "ФИО ответственного лица",
            contactsEmail = "Email",
            contactsPhone = "Телефон",
            approxClientsPerDay = "Примерное количество клиентов для анализа в день",
            approxPeopleAndFrequency = "Примерное количество человек для оценки группы/коллектива и частота проведения оценки",
            fieldAndGoal = "Сфера деятельности и цель оценки психоэмоционального состояния",
            approxEmployeesPerDay = "Примерное количество сотрудников для оценки в день",
            approxEmployeesPerDayMonth = "Примерное количество сотрудников для оценки в день/месяц",
            specialConditions = "Особые условия и пожелания",
            submitQuestionnaire = "Отправить анкету",
            questionnaireEmailSubject = "Voxera — анкета для бизнеса",
            questionnaireEmailChooserTitle = "Отправить письмо",
            questionnaireNoEmailApp = "Не найдено приложение для отправки почты",
            questionnaireIncomplete = "Выберите цель использования и заполните название организации, ФИО и email.",
            questionnaireEmailSentAt = "Дата и время отправки",
            questionnaireEmailFooter = "Письмо сформировано в приложении Voxera.",
            profile = "Профиль",
            manageSubscriptions = "Управление подписками",
            profileTitle = "Профиль",
            userName = "User",
            planBasic = "Voxera Basic",
            planBasicDesc = "3 бесплатных анализа",
            planStandard = "Voxera Standard",
            planStandardDesc = "5$/мес\nДо 30 анализов",
            planPro = "Voxera Pro",
            planProDesc = "10$/мес\n100 анализов + 3 психологических портрета",
            planUnlimited = "Voxera Unlimited",
            planUnlimitedDesc = "50$/мес\nБезлимитные анализы",
            planBusiness = "Voxera Business",
            planBusinessDesc = "Индивидуальный подход по заявкам",
            currentPlan = "Текущий план",
            profileNameLabel = "Имя",
            profilePhoneLabel = "Телефон",
            profileEmailLabel = "Эл.почта",
            profilePaymentLabel = "Способ оплаты",
            profilePhoneValue = "+**********",
            profileEmailValue = "*****@gmail.com",
            profilePaymentValue = "MasterCard ****",
            authTitle = "Вход",
            authEmail = "Email",
            authPassword = "Пароль",
            authLogin = "Войти",
            authRegister = "Зарегистрироваться",
            authGoogle = "Войти через Google",
            authSkip = "Пропустить",
            authRegisterHint = "Нет аккаунта? Зарегистрироваться",
            authLoginHint = "Уже есть аккаунт? Войти",
            authErrorInvalidEmail = "Неверный формат email",
            authErrorWeakPassword = "Пароль должен быть не менее 6 символов",
            authErrorWrongPassword = "Неверный пароль",
            authErrorUserNotFound = "Пользователь не найден",
            authErrorEmailInUse = "Email уже используется",
            authErrorGeneric = "Ошибка входа. Попробуйте снова.",
            profileEditTitle = "Редактирование профиля",
            profileChangePhoto = "Изменить фото",
            profileSignOut = "Выйти из аккаунта",
            profileGuestTitle = "Вход или регистрация",
            profileGuestName = "Гость",
            profileDone = "Готово"
        )
        val En = Strings(
            selectMode = "Select mode",
            parentMode = "Parent mode",
            parentModeSubtitle = "Psycho-emotional state of teens from age 12",
            universalMode = "Universal mode",
            universalModeSubtitle = "General assessment of psycho-emotional state",
            deepAnalysis = "Deep analysis",
            deepAnalysisSubtitle = "Creating and evaluating psychological profile",
            history = "History",
            settings = "Settings",
            onboardingText1 = "Voxera is an AI ecosystem for voice analytics. AI algorithms process speech parameters and create a digital profile of psycho-emotional state, helping you better understand and manage your condition.",
            onboardingText2 = "Voice is not just words: it reflects the work of breathing, muscles, nervous system and emotions. Voxera analyzes these signs to understand your stress level, emotional background, cognitive load, energy state and behavioral stability.",
            next = "Next",
            start = "Start",
            privacyAndConsent = "Privacy and consent",
            consentDescription = "Voxera analyzes voice features to assess current state. This is not a medical diagnosis.",
            consentVoice = "I agree to the processing of my voice data for analysis",
            consentPrivacy = "I accept the Privacy Policy and personal data processing terms",
            consentCardSummary =
                "In short: VOICElab processes audio and technical data you provide in the Voxera app to deliver the service. " +
                "This is not a medical diagnosis. The full policy is available via the link below — open it if you wish, then check the boxes to continue.",
            readFullPrivacyPolicy = "Read full Privacy Policy",
            privacyPolicyShortLink = "Privacy Policy",
            consentOpenPrivacyPolicyButton = "View privacy policy",
            privacyPolicyFullTitle = "Privacy Policy and Personal Data Processing",
            privacyPolicyFullEnglishNote = "Legal text in English.",
            back = "Back",
            voiceRecording = "Voice recording",
            recordingInProgress = "Recording...",
            tapToStart = "Tap the button to start",
            tapToStop = "Tap the button to stop recording",
            saySentences = "Say 2–3 sentences about how your day went.",
            secondsShort = "sec",
            durationHint = "At least 30 seconds",
            uploadAudio = "Upload audio",
            uploadAudioError = "Could not load the file",
            micPermissionRequired = "Microphone access is required to record",
            recordingStartFailed = "Could not start recording",
            recordingEmptyFile = "Recording is empty or too short — try again",
            analyzing = "Analyzing",
            analyzingSubtitle = "This will take a few seconds",
            result = "Result",
            emotionalBackground = "Emotional background",
            stressLevel = "Stress level",
            innerAnxiety = "Inner anxiety",
            resource = "Resource",
            tense = "Tense",
            medium = "Medium",
            mediumF = "Medium",
            reduced = "Reduced",
            share = "Share",
            newAnalysis = "New analysis",
            emostateResultTitle = "Psycho-emotional state analysis results",
            emostateParameters = "Parameters",
            emostateReportTitle = "Psycho-emotional state report",
            resultHintTitle = "Hint",
            emostateParamHintFallback =
                "This metric reflects one aspect of your voice profile in the current context. " +
                "Interpret it together with the other metrics.",
            emostateGeneralDisclaimerTitle = "General note",
            emostateGeneralDisclaimerBody =
                "Results are based on voice analysis and reflect your current state.\n" +
                "Values may change with how you feel and the situation.",
            emostateReportInfoSheetTitle = "Interpreting metrics and states",
            psytypeResultTitle = "Psychotype analysis results",
            leadingType = "Leading type",
            activeType = "Active type",
            psytypeAllTypes = "All types",
            psytypeReportTitle = "Description",
            shareResult = "Share result",
            shareNoData = "Nothing to share",
            shareSubject = "Voxera — analysis result",
            link = "Link",
            more = "More…",
            state = "State",
            stableLightTension = "Stable, light tension",
            historyTitle = "History",
            today = "Today",
            yesterday = "Yesterday",
            daysAgo = "days ago",
            twoDaysAgo = "2 days ago",
            lightTension = "Light tension",
            stable = "Stable",
            overload = "Overload",
            low = "Low",
            high = "High",
            stressLabel = "Stress",
            historyTypeEmostate = "Psycho-emotional state",
            historyTypePsytype = "Psychological profile",
            historyEmpty = "History is empty",
            statisticsButton = "Statistics",
            statisticsTitle = "Statistics",
            statisticsPeriodWeek = "Week",
            statisticsPeriodMonth = "Month",
            statisticsNoData = "Not enough data for the chart. Add psycho-emotional state analysis results.",
            settingsTitle = "Settings",
            themeTitle = "Theme",
            themeGlass = "Glass",
            themeLight = "Light",
            about = "About",
            help = "Help",
            language = "Language",
            selectLanguage = "Select language:",
            languageRu = "Русский",
            languageEn = "English",
            languageZh = "中文",
            languageKz = "Қазақша",
            aboutTitle = "About",
            aboutDescription = "Experimental voice-based state analysis. Not a medical diagnosis.",
            aboutBriefSectionTitle = "Brief overview",
            aboutFullDescriptionButton = "Full description",
            aboutPresentationNext = "Next",
            aboutPresentationDone = "Done",
            aboutResearchLinksTitle = "Research references",
            helpTitle = "Help",
            helpSubtitle = "Step-by-step tips: from choosing a mode to history and troubleshooting.",
            helpQuickStartTitle = "Quick start",
            helpQuickStartBody = "On the home screen, pick an analysis mode. Sign in if needed. On the recording screen, accept voice processing consent, tap record, and speak calmly for at least 30 seconds — follow the on-screen hints. When processing finishes, your result card opens.",
            helpRecordingTitle = "Recording and file upload",
            helpRecordingBody = "Speak at a natural pace — not whispering or shouting. Hold the phone at a comfortable distance from your mouth. To use an existing file, tap “Upload audio” and pick a supported format (e.g. WAV, MP3, M4A). Duration must meet the service requirements; clips that are too short may be rejected.",
            helpModesTitle = "Analysis modes",
            helpModesBody = "Modes cover different goals: a quick analysis, dedicated user scenarios, and an option with a psychological profile. A short description of the selected mode is shown before you record.",
            helpResultsTitle = "Results and history",
            helpResultsBody = "The result screen shows key state indicators, stress, and anxiety. Analysis history is stored on your device — you can reopen past entries from there.",
            helpPrivacyTitle = "Privacy and sharing",
            helpPrivacyBody = "Your recording is used for analysis in the chosen scenario.",
            helpTroubleshootTitle = "If something goes wrong",
            helpTroubleshootBody = "Check your internet connection and microphone permission. Try a quieter environment. For uploads, confirm the format is supported and the clip is long enough. If the error persists, try again later or with another recording.",
            forBusiness = "For Business",
            forBusinessTitle = "For Business",
            forBusinessIntro = "At this stage we offer an individual B2B approach. Our team is ready to offer you various options for using this product, for example:",
            forBusinessBullet1 = "assessment of psycho-emotional state of your clients in real-time (financial, credit organizations),",
            forBusinessBullet2 = "assessment of psycho-emotional atmosphere of employee teams,",
            forBusinessBullet3 = "assessment of fatigue and burnout level of employees,",
            forBusinessBullet4 = "assessment of psycho-emotional state of employees in responsible positions and performing critical functions,",
            forBusinessBullet5 = "assessment of psycho-emotional state of groups of children in educational systems,",
            forBusinessBullet6 = "assessment of psycho-emotional state of athletes.",
            forBusinessOutro = "We will prepare an offer specifically for your field of activity, and if necessary — integrate our product into your IT systems.\n\nTo understand your needs, please fill out a short questionnaire:",
            fillQuestionnaire = "Fill out questionnaire",
            questionnaireTitle = "Questionnaire",
            purposeOfUse = "Purpose of using the product",
            purposeFinancial = "Financial organizations for client assessment",
            purposeHrSports = "HR, sports and educational systems",
            purposeSafety = "Safety and responsible functions of employees",
            purposeOther = "Other",
            orgName = "Organization name",
            fieldOfActivity = "Field of activity",
            contacts = "Contacts",
            contactsFio = "Responsible person (full name)",
            contactsEmail = "Email",
            contactsPhone = "Phone",
            approxClientsPerDay = "Approximate number of clients for analysis per day",
            approxPeopleAndFrequency = "Approximate number of people for group/team assessment and assessment frequency",
            fieldAndGoal = "Field of activity and purpose of psycho-emotional assessment",
            approxEmployeesPerDay = "Approximate number of employees for assessment per day",
            approxEmployeesPerDayMonth = "Approximate number of employees for assessment per day/month",
            specialConditions = "Special conditions and wishes",
            submitQuestionnaire = "Submit questionnaire",
            questionnaireEmailSubject = "Voxera — business questionnaire",
            questionnaireEmailChooserTitle = "Send email",
            questionnaireNoEmailApp = "No email app found",
            questionnaireIncomplete = "Select a purpose and fill in organization name, full name, and email.",
            questionnaireEmailSentAt = "Sent at",
            questionnaireEmailFooter = "This message was generated in the Voxera app.",
            profile = "Profile",
            manageSubscriptions = "Manage subscriptions",
            profileTitle = "Profile",
            userName = "User",
            planBasic = "Voxera Basic",
            planBasicDesc = "3 free analyses",
            planStandard = "Voxera Standard",
            planStandardDesc = "$5/month, up to 30 analyses",
            planPro = "Voxera Pro",
            planProDesc = "$10/month, 100 analyses + 3 psychological portraits",
            planUnlimited = "Voxera Unlimited",
            planUnlimitedDesc = "$50/month, unlimited analyses",
            planBusiness = "Voxera Business",
            planBusinessDesc = "Individual approach by request",
            currentPlan = "Current plan",
            profileNameLabel = "Name",
            profilePhoneLabel = "Phone",
            profileEmailLabel = "Email",
            profilePaymentLabel = "Payment method",
            profilePhoneValue = "+**********",
            profileEmailValue = "*****@gmail.com",
            profilePaymentValue = "MasterCard ****",
            authTitle = "Sign in",
            authEmail = "Email",
            authPassword = "Password",
            authLogin = "Sign in",
            authRegister = "Register",
            authGoogle = "Sign in with Google",
            authSkip = "Skip",
            authRegisterHint = "No account? Register",
            authLoginHint = "Already have an account? Sign in",
            authErrorInvalidEmail = "Invalid email format",
            authErrorWeakPassword = "Password must be at least 6 characters",
            authErrorWrongPassword = "Wrong password",
            authErrorUserNotFound = "User not found",
            authErrorEmailInUse = "Email already in use",
            authErrorGeneric = "Sign in failed. Please try again.",
            profileEditTitle = "Edit profile",
            profileChangePhoto = "Change photo",
            profileSignOut = "Sign out",
            profileGuestTitle = "Sign in or register",
            profileGuestName = "Guest",
            profileDone = "Done"
        )
        val Zh = Strings(
            selectMode = "选择模式",
            parentMode = "家长模式",
            parentModeSubtitle = "12岁及以上青少年的心理情绪状态评估",
            universalMode = "通用模式",
            universalModeSubtitle = "心理情绪状态综合评估",
            deepAnalysis = "深度分析",
            deepAnalysisSubtitle = "创建和评估心理画像",
            history = "历史",
            settings = "设置",
            onboardingText1 = "Voxera是语音分析的AI生态系统。AI算法处理语音参数并创建心理情绪状态的数字档案，帮助您更好地了解和管理自己的状态。",
            onboardingText2 = "声音不仅仅是文字：它反映呼吸、肌肉、神经系统和情绪的工作。Voxera分析这些特征以了解您的压力水平、情绪背景、认知负荷、能量状态和行为稳定性。",
            next = "下一步",
            start = "开始",
            privacyAndConsent = "隐私与同意",
            consentDescription = "Voxera分析语音特征以评估当前状态。这不是医学诊断。",
            consentVoice = "我同意为分析目的处理语音数据",
            consentPrivacy = "我接受隐私政策与个人数据处理条款",
            consentCardSummary =
                "简要说明：VOICElab 会在 Voxera 应用中处理您提供的音频与技术数据以提供服务。" +
                "这不是医学诊断。完整政策见下方链接；您可随时打开阅读，然后勾选以继续。",
            readFullPrivacyPolicy = "查看完整隐私政策",
            privacyPolicyShortLink = "隐私政策",
            consentOpenPrivacyPolicyButton = "查看隐私政策",
            privacyPolicyFullTitle = "隐私政策与个人数据处理",
            privacyPolicyFullEnglishNote = "完整法律文本为英文版本。",
            back = "返回",
            voiceRecording = "语音录制",
            recordingInProgress = "录音中...",
            tapToStart = "点击按钮开始",
            tapToStop = "点击按钮停止录制",
            saySentences = "用2-3句话说说您今天过得怎么样。",
            secondsShort = "秒",
            durationHint = "至少30秒",
            uploadAudio = "上传音频",
            uploadAudioError = "无法加载文件",
            micPermissionRequired = "录音需要麦克风权限",
            recordingStartFailed = "无法开始录音",
            recordingEmptyFile = "录音为空或太短，请重试",
            analyzing = "分析中",
            analyzingSubtitle = "只需几秒钟",
            result = "结果",
            emotionalBackground = "情绪背景",
            stressLevel = "压力水平",
            innerAnxiety = "内心焦虑",
            resource = "资源",
            tense = "紧张",
            medium = "中等",
            mediumF = "中等",
            reduced = "降低",
            share = "分享",
            newAnalysis = "新分析",
            emostateResultTitle = "心理情绪状态分析结果",
            emostateParameters = "参数",
            emostateReportTitle = "心理情绪状态报告",
            resultHintTitle = "说明",
            emostateParamHintFallback =
                "该指标反映当前语境下声音特征的一个方面。请结合其他指标综合理解。",
            emostateGeneralDisclaimerTitle = "总体说明",
            emostateGeneralDisclaimerBody =
                "结果基于语音分析，反映当前状态。\n数值可能随身体状况与场景而变化。",
            emostateReportInfoSheetTitle = "指标与状态的解读",
            psytypeResultTitle = "心理类型分析结果",
            leadingType = "主导类型",
            activeType = "活跃类型",
            psytypeAllTypes = "所有类型",
            psytypeReportTitle = "描述",
            shareResult = "分享结果",
            shareNoData = "暂无可分享内容",
            shareSubject = "Voxera — 分析结果",
            link = "链接",
            more = "更多…",
            state = "状态",
            stableLightTension = "稳定，轻度紧张",
            historyTitle = "历史",
            today = "今天",
            yesterday = "昨天",
            daysAgo = "天前",
            twoDaysAgo = "2天前",
            lightTension = "轻度紧张",
            stable = "稳定",
            overload = "过载",
            low = "低",
            high = "高",
            stressLabel = "压力",
            historyTypeEmostate = "心理情绪状态",
            historyTypePsytype = "心理画像",
            historyEmpty = "历史为空",
            statisticsButton = "统计",
            statisticsTitle = "统计",
            statisticsPeriodWeek = "周",
            statisticsPeriodMonth = "月",
            statisticsNoData = "图表数据不足。请添加心理情绪状态分析结果。",
            settingsTitle = "设置",
            themeTitle = "主题",
            themeGlass = "玻璃",
            themeLight = "浅色",
            about = "关于",
            help = "帮助",
            language = "语言",
            selectLanguage = "选择语言：",
            languageRu = "Русский",
            languageEn = "English",
            languageZh = "中文",
            languageKz = "Қазақша",
            aboutTitle = "关于",
            aboutDescription = "实验性语音状态分析。非医学诊断。",
            aboutBriefSectionTitle = "简要说明",
            aboutFullDescriptionButton = "完整说明",
            aboutPresentationNext = "下一步",
            aboutPresentationDone = "完成",
            aboutResearchLinksTitle = "研究文献链接",
            helpTitle = "帮助",
            helpSubtitle = "分步说明：从选择模式到历史记录与故障排除。",
            helpQuickStartTitle = "快速开始",
            helpQuickStartBody = "在主界面选择分析模式。如需请先登录。在录音界面同意语音处理，然后点击录音，平静朗读至少30秒，并遵循屏幕提示。处理完成后会打开结果卡片。",
            helpRecordingTitle = "录音与上传文件",
            helpRecordingBody = "以自然语速说话，避免耳语或喊叫。手机与口部保持舒适距离。若使用已有文件，请点击“上传音频”并选择支持的格式（如 WAV、MP3、M4A）。时长须符合服务要求，过短可能被拒绝。",
            helpModesTitle = "分析模式",
            helpModesBody = "不同模式对应不同目的：快速分析、专用场景以及含心理画像的选项。录音前会显示所选模式的简要说明。",
            helpResultsTitle = "结果与历史",
            helpResultsBody = "结果页展示主要状态指标、压力与焦虑。分析记录保存在本机，可从历史入口再次查看。",
            helpPrivacyTitle = "隐私与分享",
            helpPrivacyBody = "录音仅用于所选场景下的分析。",
            helpTroubleshootTitle = "出现问题时",
            helpTroubleshootBody = "请检查网络与麦克风权限，尝试在更安静环境录音。上传文件时请确认格式受支持且时长足够。若仍失败，可稍后再试或更换片段。",
            forBusiness = "企业版",
            forBusinessTitle = "企业版",
            forBusinessIntro = "现阶段我们提供个性化B2B方案。我们的团队随时准备为您提供各种产品使用选项，例如：",
            forBusinessBullet1 = "实时评估客户心理情绪状态（金融、信贷机构），",
            forBusinessBullet2 = "评估员工团队心理情绪氛围，",
            forBusinessBullet3 = "评估员工疲劳和倦怠程度，",
            forBusinessBullet4 = "评估担任重要职位和执行关键职能的员工心理情绪状态，",
            forBusinessBullet5 = "评估教育系统中儿童群体的心理情绪状态，",
            forBusinessBullet6 = "评估运动员的心理情绪状态。",
            forBusinessOutro = "我们将为您的行业量身定制方案，必要时可将我们的产品集成到您的IT系统中。\n\n为了解您的需求，请填写简短问卷：",
            fillQuestionnaire = "填写问卷",
            questionnaireTitle = "问卷",
            purposeOfUse = "产品使用目的",
            purposeFinancial = "金融机构客户评估",
            purposeHrSports = "人力资源、体育和教育系统",
            purposeSafety = "安全和员工关键职能",
            purposeOther = "其他",
            orgName = "组织名称",
            fieldOfActivity = "业务领域",
            contacts = "联系方式",
            contactsFio = "负责人（全名）",
            contactsEmail = "电子邮件",
            contactsPhone = "电话",
            approxClientsPerDay = "每日分析客户的大致数量",
            approxPeopleAndFrequency = "群体/团队评估的大致人数和评估频率",
            fieldAndGoal = "业务领域和心理情绪评估目的",
            approxEmployeesPerDay = "每日评估员工的大致数量",
            approxEmployeesPerDayMonth = "每日/每月评估员工的大致数量",
            specialConditions = "特殊条件和愿望",
            submitQuestionnaire = "提交问卷",
            questionnaireEmailSubject = "Voxera — 企业问卷",
            questionnaireEmailChooserTitle = "发送邮件",
            questionnaireNoEmailApp = "未找到邮件应用",
            questionnaireIncomplete = "请选择使用目的，并填写组织名称、姓名和电子邮件。",
            questionnaireEmailSentAt = "发送时间",
            questionnaireEmailFooter = "此邮件由 Voxera 应用生成。",
            profile = "个人资料",
            manageSubscriptions = "管理订阅",
            profileTitle = "个人资料",
            userName = "User",
            planBasic = "Voxera Basic",
            planBasicDesc = "3次免费分析",
            planStandard = "Voxera Standard",
            planStandardDesc = "每月5美元，最多30次分析",
            planPro = "Voxera Pro",
            planProDesc = "每月10美元，100次分析+3个心理画像",
            planUnlimited = "Voxera Unlimited",
            planUnlimitedDesc = "每月50美元，无限次分析",
            planBusiness = "Voxera Business",
            planBusinessDesc = "根据申请提供个性化方案",
            currentPlan = "当前计划",
            profileNameLabel = "姓名",
            profilePhoneLabel = "电话",
            profileEmailLabel = "电子邮件",
            profilePaymentLabel = "支付方式",
            profilePhoneValue = "+**********",
            profileEmailValue = "*****@gmail.com",
            profilePaymentValue = "MasterCard ****",
            authTitle = "登录",
            authEmail = "电子邮件",
            authPassword = "密码",
            authLogin = "登录",
            authRegister = "注册",
            authGoogle = "使用 Google 登录",
            authSkip = "跳过",
            authRegisterHint = "没有账户？注册",
            authLoginHint = "已有账户？登录",
            authErrorInvalidEmail = "电子邮件格式无效",
            authErrorWeakPassword = "密码至少6个字符",
            authErrorWrongPassword = "密码错误",
            authErrorUserNotFound = "未找到用户",
            authErrorEmailInUse = "电子邮件已被使用",
            authErrorGeneric = "登录失败，请重试。",
            profileEditTitle = "编辑个人资料",
            profileChangePhoto = "更换照片",
            profileSignOut = "退出登录",
            profileGuestTitle = "登录或注册",
            profileGuestName = "访客",
            profileDone = "完成"
        )
        val Kz = Strings(
            selectMode = "Режимді таңдаңыз",
            parentMode = "Ата-ана режимі",
            parentModeSubtitle = "12 жастан бастап жасөспірімнің психоэмоционалдық күйін бағалау",
            universalMode = "Жалпы режим",
            universalModeSubtitle = "Психоэмоционалдық жағдайды жалпы бағалау",
            deepAnalysis = "Терең талдау",
            deepAnalysisSubtitle = "Психологиялық портрет құру және бағалау",
            history = "Тарих",
            settings = "Баптаулар",
            onboardingText1 = "Voxera — дауыс аналитикасының AI экожүйесі. AI алгоритмдері сөйлеу параметрлерін өңдейді және психоэмоционалдық жағдайдың сандық профилін құрады, өзіңізді жақсырақ түсінуге және жағдайыңызды басқаруға көмектеседі.",
            onboardingText2 = "Дауыс — тек сөздер емес: ол тыныс алу, бұлшықеттер, жүйке жүйесі және эмоциялардың жұмысын көрсетеді. Voxera стресс деңгейіңізді, эмоционалды фонды, когнитивтік жүктемені, энергетикалық жағдайды және мінез-құлық тұрақтылығын түсіну үшін осы белгілерді талдайды.",
            next = "Келесі",
            start = "Бастау",
            privacyAndConsent = "Құпиялылық және келісім",
            consentDescription = "Voxera ағымдағы жағдайды бағалау үшін дауыс белгілерін талдайды. Бұл медициналық диагноз емес.",
            consentVoice = "Талдау үшін дауыс деректерін өңдеуге келісемін",
            consentPrivacy = "Құпиялылық саясатын және жеке деректерді өңдеу шарттарын қабылдаймын",
            consentCardSummary =
                "Қысқаша: VOICElab Voxera қолданбасында сіз берген аудио және техникалық деректерді қызмет көрсету үшін өңдейді. " +
                "Бұл медициналық диагноз емес. Толық саясат төмендегі сілтемеде; қалағанда оқыңыз, содан кейін белгілерді қойыңыз.",
            readFullPrivacyPolicy = "Толық құпиялылық саясатын ашу",
            privacyPolicyShortLink = "Құпиялылық саясаты",
            consentOpenPrivacyPolicyButton = "Құпиялылық саясатын оқу",
            privacyPolicyFullTitle = "Құпиялылық және жеке деректерді өңдеу саясаты",
            privacyPolicyFullEnglishNote = "Толық заңи мәтін ағылшын тілінде.",
            back = "Артқа",
            voiceRecording = "Дауыс жазу",
            recordingInProgress = "Жазуда...",
            tapToStart = "Бастау үшін батырманы басыңыз",
            tapToStop = "Жазуды тоқтату үшін батырманы басыңыз",
            saySentences = "Күніңіз қалай өткенін 2-3 сөйлеммен айтыңыз.",
            secondsShort = "сек",
            durationHint = "Кемінде 30 секунд",
            uploadAudio = "Аудио жүктеу",
            uploadAudioError = "Файл жүктелмеді",
            micPermissionRequired = "Жазу үшін микрофон рұқсаты қажет",
            recordingStartFailed = "Жазуды бастау мүмкін болмады",
            recordingEmptyFile = "Жазу бос немесе тым қысқа — қайталаңыз",
            analyzing = "Талдауда",
            analyzingSubtitle = "Бірнеше секунд қажет",
            result = "Нәтиже",
            emotionalBackground = "Эмоционалды фон",
            stressLevel = "Стресс деңгейі",
            innerAnxiety = "Ішкі алаңдаушылық",
            resource = "Ресурс",
            tense = "Кернеулі",
            medium = "Орташа",
            mediumF = "Орташа",
            reduced = "Төмендеген",
            share = "Бөлісу",
            newAnalysis = "Жаңа талдау",
            emostateResultTitle = "Психоэмоционалды күй талдау нәтижелері",
            emostateParameters = "Параметрлер",
            emostateReportTitle = "Психоэмоционалды күй туралы есеп",
            resultHintTitle = "Кеңес",
            emostateParamHintFallback =
                "Бұл көрсеткіс дауыстық профильдің ағымдағы контекстегі бір жақтарын көрсетеді. " +
                "Басқа метрикалармен бірге қараңыз.",
            emostateGeneralDisclaimerTitle = "Жалпы кеңес",
            emostateGeneralDisclaimerBody =
                "Нәтижелер дауысты талдауға негізделген және ағымдағы күйді көрсетеді.\n" +
                "Мәндер денсаулық пен жағдайға байланысты өзгеруі мүмкін.",
            emostateReportInfoSheetTitle = "Метрикалар мен күйлерді түсіндіру",
            psytypeResultTitle = "Психотип талдау нәтижелері",
            leadingType = "Жетекші тип",
            activeType = "Белсенді тип",
            psytypeAllTypes = "Барлық типтер",
            psytypeReportTitle = "Сипаттама",
            shareResult = "Нәтижені бөлісу",
            shareNoData = "Бөлісу үшін дерек жоқ",
            shareSubject = "Voxera — талдау нәтижесі",
            link = "Сілтеме",
            more = "Тағы…",
            state = "Жағдай",
            stableLightTension = "Тұрақты, жеңіл кернеу",
            historyTitle = "Тарих",
            today = "Бүгін",
            yesterday = "Кеше",
            daysAgo = "күн бұрын",
            twoDaysAgo = "2 күн бұрын",
            lightTension = "Жеңіл кернеу",
            stable = "Тұрақты",
            overload = "Жүктеме",
            low = "Төмен",
            high = "Жоғары",
            stressLabel = "Стресс",
            historyTypeEmostate = "Психоэмоционалдық жағдай",
            historyTypePsytype = "Психологиялық портрет",
            historyEmpty = "Тарих бос",
            statisticsButton = "Статистика",
            statisticsTitle = "Статистика",
            statisticsPeriodWeek = "Апта",
            statisticsPeriodMonth = "Ай",
            statisticsNoData = "Диаграмма үшін деректер жеткіліксіз. Психоэмоционалдық күй талдау нәтижелерін қосыңыз.",
            settingsTitle = "Баптаулар",
            themeTitle = "Тақырып",
            themeGlass = "Шыны",
            themeLight = "Жарық",
            about = "Қолданба туралы",
            help = "Көмек",
            language = "Тіл",
            selectLanguage = "Тілді таңдаңыз:",
            languageRu = "Русский",
            languageEn = "English",
            languageZh = "中文",
            languageKz = "Қазақша",
            aboutTitle = "Қолданба туралы",
            aboutDescription = "Дауыс бойынша жағдайды тәжірибелік талдау. Медициналық диагноз емес.",
            aboutBriefSectionTitle = "Қысқаша сипаттама",
            aboutFullDescriptionButton = "Толық сипаттама",
            aboutPresentationNext = "Келесі",
            aboutPresentationDone = "Дайын",
            aboutResearchLinksTitle = "Зерттеу сілтемелері",
            helpTitle = "Көмек",
            helpSubtitle = "Қадамдар бойынша кеңестер: режимді таңдаудан тарих пен ақауларды жоюға дейін.",
            helpQuickStartTitle = "Жылдам бастау",
            helpQuickStartBody = "Басты экранда талдау режимін таңдаңыз. Қажет болса аккаунтқа кіріңіз. Жазу экранында дауыс өңдеуге келісім беріңіз, содан кейін жазу түймесін басыңыз да кемінде 30 секунд спокойлы сөйлеңіз — экрандағы кеңестерді орындаңыз. Өңдеу аяқталғаннан кейін нәтиже карточкасы ашылады.",
            helpRecordingTitle = "Жазу және файл жүктеу",
            helpRecordingBody = "Табиғи темпте сөйлеңіз — сыбырламаңыз және айқайламаңыз. Телефонды ауыздан ыңғайлы қашықтықта ұстаңыз. Дайын файлды пайдаланғыңыз келсе — «Аудио жүктеу» түймесін басыңыз да қолданылатын форматты таңдаңыз (мысалы WAV, MP3, M4A). Ұзындық қызмет талаптарына сай болуы керек; тым қысқа фрагмент қабылданбауы мүмкін.",
            helpModesTitle = "Талдау режимдері",
            helpModesBody = "Әртүрлі мақсаттарға арналған сценарийлер бар: жылдам талдау, арнайы режимдер және психологиялық портрет опциясы. Жазбас бұрын таңдалған режимнің қысқаша сипаттамасы көрсетіледі.",
            helpResultsTitle = "Нәтиже және тарих",
            helpResultsBody = "Нәтиже экранында негізгі көрсеткіштер, стресс пен мазасыздық көрінеді. Талдаулар құрылғыда сақталады — өткен жазбаларды қайта ашуға болады.",
            helpPrivacyTitle = "Құпиялылық және бөлісу",
            helpPrivacyBody = "Жазба таңдалған сценарий шеңберінде талдау үшін пайдаланылады.",
            helpTroubleshootTitle = "Бірдеңе дұрыс болмаса",
            helpTroubleshootBody = "Интернет пен микрофон рұқсатын тексеріңіз. Тыныш ортада жазуға тырысыңыз. Файл жүктегенде формат пен ұзындық сәйкес екенін растаңыз. Қате қайталанса — кейінірек қайталаңыз немесе басқа фрагментті пайдаланыңыз.",
            forBusiness = "Бизнес үшін",
            forBusinessTitle = "Бизнес үшін",
            forBusinessIntro = "Осы кезеңде біз B2B-ге жеке тәсілді қолданамыз. Біздің команда осы өнімді пайдаланудың әртүрлі нұсқаларын ұсынуға дайын, мысалы:",
            forBusinessBullet1 = "клиенттердің психоэмоционалдық жағдайын нақты уақытта бағалау (қаржылық, несиелік ұйымдар),",
            forBusinessBullet2 = "қызметкерлер тобының психоэмоционалдық атмосферасын бағалау,",
            forBusinessBullet3 = "қызметкерлердің шаршауы мен күйіну деңгейін бағалау,",
            forBusinessBullet4 = "жауапты лауазымдарда және маңызды функцияларды орындайтын қызметкерлердің психоэмоционалдық жағдайын бағалау,",
            forBusinessBullet5 = "білім беру жүйелеріндегі балалар тобының психоэмоционалдық жағдайын бағалау,",
            forBusinessBullet6 = "спортшылардың психоэмоционалдық жағдайын бағалау.",
            forBusinessOutro = "Біз сіздің қызмет салаңызға арнайы ұсыныс дайындаймыз, қажет болса — өнімімізді сіздің АҚ жүйелеріңізге интеграциялаймыз.\n\nҚажеттіліктеріңізді түсіну үшін қысқа сауалнаманы толтырыңыз:",
            fillQuestionnaire = "Сауалнаманы толтыру",
            questionnaireTitle = "Сауалнама",
            purposeOfUse = "Өнімді пайдалану мақсаты",
            purposeFinancial = "Клиенттерді бағалау үшін қаржылық ұйымдар",
            purposeHrSports = "HR, спорт және білім беру жүйелері",
            purposeSafety = "Қауіпсіздік және қызметкерлердің жауапты функциялары",
            purposeOther = "Басқа",
            orgName = "Ұйым атауы",
            fieldOfActivity = "Қызмет саласы",
            contacts = "Байланыс",
            contactsFio = "Жауапты тұлға (ТАӘ)",
            contactsEmail = "Email",
            contactsPhone = "Телефон",
            approxClientsPerDay = "Күніне талдау үшін клиенттердің шамамен саны",
            approxPeopleAndFrequency = "Топ/коллективті бағалау үшін адамдардың шамамен саны және бағалау жиілігі",
            fieldAndGoal = "Қызмет саласы және психоэмоционалдық бағалау мақсаты",
            approxEmployeesPerDay = "Күніне бағалау үшін қызметкерлердің шамамен саны",
            approxEmployeesPerDayMonth = "Күніне/айына бағалау үшін қызметкерлердің шамамен саны",
            specialConditions = "Арнайы шарттар мен тілектер",
            submitQuestionnaire = "Сауалнаманы жіберу",
            questionnaireEmailSubject = "Voxera — бизнес сауалнамасы",
            questionnaireEmailChooserTitle = "Хат жіберу",
            questionnaireNoEmailApp = "Пошта қолданбасы табылмады",
            questionnaireIncomplete = "Пайдалану мақсатын таңдаңыз және ұйым атауы, ТАӘ және email толтырыңыз.",
            questionnaireEmailSentAt = "Жіберілген уақыты",
            questionnaireEmailFooter = "Хат Voxera қолданбасында қалыпталған.",
            profile = "Профиль",
            manageSubscriptions = "Жазылымдарды басқару",
            profileTitle = "Профиль",
            userName = "User",
            planBasic = "Voxera Basic",
            planBasicDesc = "3 тегін талдау",
            planStandard = "Voxera Standard",
            planStandardDesc = "Айына 5 доллар, 30 талдауға дейін",
            planPro = "Voxera Pro",
            planProDesc = "Айына 10 доллар, 100 талдау + 3 психологиялық портрет",
            planUnlimited = "Voxera Unlimited",
            planUnlimitedDesc = "Айына 50 доллар, шексіз талдаулар",
            planBusiness = "Voxera Business",
            planBusinessDesc = "Өтініш бойынша жеке тәсіл",
            currentPlan = "Ағымдағы жоспар",
            profileNameLabel = "Аты",
            profilePhoneLabel = "Телефон",
            profileEmailLabel = "Эл.пошта",
            profilePaymentLabel = "Төлем әдісі",
            profilePhoneValue = "+**********",
            profileEmailValue = "*****@gmail.com",
            profilePaymentValue = "MasterCard ****",
            authTitle = "Кіру",
            authEmail = "Email",
            authPassword = "Құпия сөз",
            authLogin = "Кіру",
            authRegister = "Тіркелу",
            authGoogle = "Google арқылы кіру",
            authSkip = "Өткізіп жіберу",
            authRegisterHint = "Аккаунт жоқ па? Тіркеліңіз",
            authLoginHint = "Аккаунтыңыз бар ма? Кіріңіз",
            authErrorInvalidEmail = "Email форматы қате",
            authErrorWeakPassword = "Құпия сөз кем дегенде 6 таңбадан тұруы керек",
            authErrorWrongPassword = "Құпия сөз қате",
            authErrorUserNotFound = "Пайдаланушы табылмады",
            authErrorEmailInUse = "Email қолданыста",
            authErrorGeneric = "Кіру сәтсіз аяқталды. Қайталап көріңіз.",
            profileEditTitle = "Профильді өңдеу",
            profileChangePhoto = "Фотоны өзгерту",
            profileSignOut = "Шығу",
            profileGuestTitle = "Кіру немесе тіркелу",
            profileGuestName = "Қонақ",
            profileDone = "Дайын"
        )
    }
}
